SHOTS_DATA = [
    {"id": "GA1020", "label": "GA1020", "time_range": "00:00–1:04", "notes": "Both GA shots are cutaways in the commercial. Match roughly using our train; train can move faster, not slower. Beauty shots: no overcast, no excessive atmosphere, no city backdrop. Exterior outside train window does not have to match wide shots cut-to-cut."},
    {"id": "GA1100", "label": "GA1100", "time_range": "1:15–2:25", "notes": "No unattractive trailers/cars on floor. Focus on train in beautiful environment (especially crossing bridge). Train must not appear electric—avoid poles/electric lines above bridge. Train look consistent, no electric features. Bright appealing blue sky; not dreary. Current speed good; be ready to adjust (e.g. double speed). Minor tweaks expected."},
    {"id": "CC1540", "label": "CC1540", "time_range": "2:41–4:14", "notes": "Train approaching haunted area; they like the atmosphere. Do not use full length of stock—only relevant portion with our train. Train should not go on forever; limit visible length. Use count sheets for time codes and stock segments. Start with engine + eight cars; keep consistent. Use reference for color."},
    {"id": "CC1920", "label": "CC1920", "time_range": "4:22–5:09", "notes": "Train moving too slowly—should be faster. Approach to haunted tunnel; atmosphere and ambiance work well, tie environments together. Overhead gag not preferred but not major. Match camera angles from reference."},
    {"id": "CC1920_2", "label": "CC1920 (2)", "time_range": "5:09–6:08", "notes": "Switch shot: train approaching switch, then arriving by switch when it completes. Emphasize switch action at last moment (hand play / humor). Heat shimmer effect does not need to be matched."},
    {"id": "MT1420", "label": "MT1420", "time_range": "6:24–7:08", "notes": "Wheel slightly comes off track, sparks. Match what's here best you can. Do not spend too much time; may be fine as is."},
    {"id": "CF4240", "label": "CF4240", "time_range": "7:47–9:40", "notes": "Keep falling character as separate element for future feedback (timing, delay, slow down). Camera: stabilizing when pulling back likely OK; don't focus on shake. Sometimes final frame + clear instructions works better than whole sequence. Equal effort on environment and train for approvals."},
    {"id": "CF1000", "label": "CF1000", "time_range": "9:41–11:25", "notes": "BG from still of stock doesn't work. New angle looking down ravine for depth (even still render). Background too close—environment/ravine much wider and deeper. After AI delivers environment, generate angle from above train looking down into ravine. Work wide and downward angle together for consistency. Prioritize wider/deeper environment over fall position."},
    {"id": "CF4240_plate", "label": "CF4240 (plate depth)", "time_range": "11:31–12:30", "notes": "Make depth below train twice as deep for this plate."},
    {"id": "SC1600", "label": "SC1600", "time_range": "13:03–16:28", "notes": "Calm then train enters rapidly approaching storm. Lightning strikes train—two bolts: first in wide (environment); second hits train (new shot, e.g. SC1610). Camera off to side, locked, train moves past; lightning physically hitting top of train. Storm in front of train. Use cut timing: first bolt environment only, second bolt hits train. Beginning of storm—not extreme weather yet."},
    {"id": "VT1000", "label": "VT1000", "time_range": "17:07–19:44", "notes": "Same storm as SC1600; consistency in atmosphere and lighting. Different camera angle for train-hit-by-lightning vs SC1600. Train moving away so we see storm. Creative freedom; bullet-train speed (continent in ~4.5h). Use reference mainly for camera angle; environment/lighting from approved refs. Stormy, not bright/sunny."},
    {"id": "BT1820", "label": "BT1820", "time_range": "28:48–29:53", "notes": "Underwater storm environment; joke about excessive rainfall. Not tropical underwater. Creative freedom. Blowfish as separate element; may need independent adjustments (humorous/rude actions)."},
]
